### ISSUE TITLE
TH-D72A

### ISSUE THREAD

**Issue by sallevan** [LA3QMA/TH-D72-Kenwood#2]
ty
TY A,M,B,1

(as feedback)

**Comment by LA3QMA** [comment]
Is this radio modified? "Hardware extended TX modified"?

73 de LA3QMA

man. 9. nov. 2020, 15:40 skrev Andrew Kolchoogin <notifications@github.com>:

**Comment by sallevan** [comment]
> Is this radio modified? "Hardware extended TX modified"?

Please explain what does it mean: I made no modifications by myself, radio was officially bought in the U.S.A.

73 de R2DOU

**Comment by LA3QMA** [comment]
If you modify the rx/tx range the radio is reporting this as a different value. If you are not sure if the radio is modified or not i'm updating the data to be an "unmodified". We can always change this later if some one can confirm the result from an unmodified radio.

**Comment by sallevan** [comment]
> If you modify the rx/tx range the radio is reporting this as a different value.

I'm sure that radio was not modified in any way.
