### ISSUE TITLE
Port Speed

### ISSUE THREAD

**Issue by JeffHochberg** [LA3QMA/TH-D72-Kenwood#3]
What baud rate did you use when testing? 9600? 38400? From what I've found, it looks like it should be 9600, but wanted to confirm what your findings were.

**Comment by LA3QMA** [comment]
To control the radio it's 9600bd.

Starting the upgrade command "0M PROGRAM" i think you have to change to faster baud rate when up/downloading firmware.
But all the regular commands is done in 9600bd.
